fixtures:
  forge_modules:
    archive:
      repo: puppet/archive
      ref: 0.5.1
    augeas_core:
      repo: puppetlabs/augeas_core
      ref: 1.0.4
    stdlib:
      repo: puppetlabs/stdlib
      ref: 4.13.1
    java:
      repo: puppetlabs/java
      ref: 6.5.0
    concat:
      repo: puppetlabs/concat
      ref: 2.2.1
    datacat:
      repo: richardc/datacat
      ref: 0.6.2
    apt:
      repo: puppetlabs/apt
      ref: 7.4.1
    zypprepo:
      repo: puppet/zypprepo
      ref: 2.2.2
    yumrepo_core:
      repo: puppetlabs/yumrepo_core
      ref: 1.0.3
    java_ks: puppetlabs/java_ks
    elastic_stack:
      repo: elastic/elastic_stack
      ref: 6.1.0
  symlinks:
    elasticsearch: "#{source_dir}"
