name    'haf-elasticsearch'
version '0.2.0'
source 'https://github.com/haf/puppet-elasticsearch'
author 'ispavailability'
license 'Apache License, Version 2.0'
summary 'Module for managing and configuring Elasticsearch nodes'
description 'Module for managing and configuring Elasticsearch nodes'
project_page 'https://github.com/elasticsearch/puppet-elasticsearch'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
dependency 'puppetlabs/java', '>= 1.0.1'
