name    'elasticsearch-elasticsearch'
version '0.9.3'
source 'https://github.com/elastic/puppet-elasticsearch'
author 'elasticsearch'
license 'Apache License, Version 2.0'
summary 'Module for managing and configuring Elasticsearch nodes'
description 'Module for managing and configuring Elasticsearch nodes'
project_page 'https://github.com/elastic/puppet-elasticsearch'
dependency 'puppetlabs/stdlib', '>= 3.2.0 < 5.0.0'
