name    'ispavailability-elasticsearch'
version '0.1.3'
source 'https://github.com/elasticsearch/puppet-elasticsearch'
author 'ispavailability'
license 'Apache License, Version 2.0'
summary 'Module for managing and configuring Elasticsearch nodes'
description 'Module for managing and configuring Elasticsearch nodes'
project_page 'https://github.com/elasticsearch/puppet-elasticsearch'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
